# Generated by Django 2.1a1 on 2018-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1000)),
                ('t_Creator', models.CharField(max_length=250)),
                ('t_Assigned', models.CharField(max_length=250)),
                ('t_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
