# Generated by Django 2.1a1 on 2018-06-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmanager',
            old_name='t_Status',
            new_name='t_Done',
        ),
    ]
